on:
  push:
    branches:
      - master

name: Create Tag

permissions:
  contents: write

jobs:

  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest

    outputs:
      create_release: ${{ steps.create_release_check.outputs.create_release }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Get current version
        run: |
          echo release_version="$(cat version.txt)" >> $GITHUB_ENV

      - name: See if version exists
        id: create_release_check
        run: |
          if [[ $(git tag -l v$release_version) ]]; then
            echo Version v$release_version already exists.;
            echo "create_release=false" >> "$GITHUB_OUTPUT";
          else
            echo "create_release=true" >> "$GITHUB_OUTPUT";
            git tag v$release_version;
            git push origin v$release_version;
          fi

  # Conditional on if we have a new tag
  create_release:
    needs: create_tag

    name: Create Release
    runs-on: ubuntu-latest

    if: ${{ needs.create_tag.outputs.create_release == 'true' }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Tag
        run:  echo release_version="$(cat version.txt)" >> $GITHUB_ENV

      - name: Authenticate on GCS
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '290.0.1'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            hawk_eye/setup/requirements.txt
            hawk_eye/setup/requirements-cpu.txt
            hawk_eye/setup/requirements-gpu.txt

      - name: Setup Machine
        run: hawk_eye/setup/setup_env.sh

      - name: Ensure Tests Run
        run: ./setup.py test

      - name: Create hawk_eye .whl package
        run: ./setup.py bdist_wheel

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.release_version }}
          name: Release v${{ env.release_version }}
          files: ./dist/hawk_eye-${{ env.release_version }}-py3-none-any.whl
