name: deploy-docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:

  build-docs:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: docs/requirements.txt

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r docs/requirements.txt

    - name: make-docs
      run: |
        cd docs/source
        sphinx-build -W --keep-going -b html . _build

    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: docs/source/_build
